version: "3.9"

services:
  library-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - h2-db
    networks:
      - library-network

  h2-db:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -ifNotExists"
    networks:
      - library-network

networks:
  library-network:
    driver: bridge